/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsaapRouteImport } from './routes/asaap'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as AsaapIndexRouteImport } from './routes/asaap/index'
import { Route as AsaapSecaoRouteImport } from './routes/asaap/$secao'
import { Route as ClienteIndexRouteImport } from './routes/cliente/index'
import { Route as ClienteSecaoRouteImport } from './routes/cliente/$secao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsaapRoute = AsaapRouteImport.update({
  id: '/asaap',
  path: '/asaap',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const AsaapIndexRoute = AsaapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AsaapRoute,
} as any)
const AsaapSecaoRoute = AsaapSecaoRouteImport.update({
  id: '/$secao',
  path: '/$secao',
  getParentRoute: () => AsaapRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteSecaoRoute = ClienteSecaoRouteImport.update({
  id: '/$secao',
  path: '/$secao',
  getParentRoute: () => ClienteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asaap': typeof AsaapRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/dados': typeof DadosRoute
  '/asaap/$secao': typeof AsaapSecaoRoute
  '/cliente/$secao': typeof ClienteSecaoRoute
  '/asaap/': typeof AsaapIndexRoute
  '/cliente/': typeof ClienteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/asaap/$secao': typeof AsaapSecaoRoute
  '/cliente/$secao': typeof ClienteSecaoRoute
  '/asaap': typeof AsaapIndexRoute
  '/cliente': typeof ClienteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asaap': typeof AsaapRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/dados': typeof DadosRoute
  '/asaap/$secao': typeof AsaapSecaoRoute
  '/cliente/$secao': typeof ClienteSecaoRoute
  '/asaap/': typeof AsaapIndexRoute
  '/cliente/': typeof ClienteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asaap'
    | '/cliente'
    | '/dados'
    | '/asaap/$secao'
    | '/cliente/$secao'
    | '/asaap/'
    | '/cliente/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/dados' | '/asaap/$secao' | '/cliente/$secao' | '/asaap' | '/cliente'
  id:
    | '__root__'
    | '/'
    | '/asaap'
    | '/cliente'
    | '/dados'
    | '/asaap/$secao'
    | '/cliente/$secao'
    | '/asaap/'
    | '/cliente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsaapRoute: typeof AsaapRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  DadosRoute: typeof DadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asaap': {
      id: '/asaap'
      path: '/asaap'
      fullPath: '/asaap'
      preLoaderRoute: typeof AsaapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asaap/': {
      id: '/asaap/'
      path: '/'
      fullPath: '/asaap/'
      preLoaderRoute: typeof AsaapIndexRouteImport
      parentRoute: typeof AsaapRoute
    }
    '/asaap/$secao': {
      id: '/asaap/$secao'
      path: '/$secao'
      fullPath: '/asaap/$secao'
      preLoaderRoute: typeof AsaapSecaoRouteImport
      parentRoute: typeof AsaapRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/$secao': {
      id: '/cliente/$secao'
      path: '/$secao'
      fullPath: '/cliente/$secao'
      preLoaderRoute: typeof ClienteSecaoRouteImport
      parentRoute: typeof ClienteRoute
    }
  }
}

interface AsaapRouteChildren {
  AsaapSecaoRoute: typeof AsaapSecaoRoute
  AsaapIndexRoute: typeof AsaapIndexRoute
}

const AsaapRouteChildren: AsaapRouteChildren = {
  AsaapSecaoRoute: AsaapSecaoRoute,
  AsaapIndexRoute: AsaapIndexRoute,
}

const AsaapRouteWithChildren = AsaapRoute._addFileChildren(AsaapRouteChildren)

interface ClienteRouteChildren {
  ClienteSecaoRoute: typeof ClienteSecaoRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteSecaoRoute: ClienteSecaoRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsaapRoute: AsaapRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  DadosRoute: DadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
